"use client";
import Link from "next/link";
import { Brain, ChevronRight, Dice5, GitBranch } from "lucide-react";

const SUBTOPICS = [
  { id: "basic", href: "/3u/topic/grade11/probability/basic", icon: Dice5, title: "הסתברות בסיסית", subtitle: "מרחב מדגם • אירועים • חיתוך ואיחוד", description: "הגדרת מרחב מדגם, חישוב הסתברות של אירועים, כללי חיתוך ואיחוד.", chips: ["P(A∪B)", "P(A∩B)", "מרחב מדגם"], ready: true, glowAnim: true, iconBg: "bg-purple-500/10", iconBorder: "border-purple-500/30", iconText: "text-purple-400", hoverBorder: "hover:border-purple-500/50", badgeBg: "bg-purple-500/10 border-purple-500/30", badgeText: "text-purple-400", chevronHover: "group-hover:text-purple-400" },
  { id: "conditional", href: "/3u/topic/grade11/probability/conditional", icon: GitBranch, title: "הסתברות מותנית", subtitle: "P(A|B) • עצי הסתברות • בייס", description: "חישוב הסתברות מותנית, בניית עץ הסתברות, ונוסחת בייס.", chips: ["P(A|B)", "עץ הסתברות", "בייס"], ready: true, glowAnim: false, iconBg: "bg-violet-500/10", iconBorder: "border-violet-500/30", iconText: "text-violet-400", hoverBorder: "hover:border-violet-500/50", badgeBg: "bg-violet-500/10 border-violet-500/30", badgeText: "text-violet-400", chevronHover: "group-hover:text-violet-400" },
] as const;

export default function ProbabilityHub3u() {
  return (
    <div className="min-h-screen bg-[#0a0f1e] text-white" dir="rtl">
      <style>{`@keyframes fadeSlideIn{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}@keyframes pulseGlow{0%,100%{box-shadow:0 0 0 0 rgba(168,85,247,0)}50%{box-shadow:0 0 20px 5px rgba(168,85,247,0.13)}}.card-hover{transition:transform .18s ease,border-color .18s ease}.card-hover:hover{transform:translateY(-3px)}`}</style>
      <header className="bg-[#0f172a] border-b border-slate-800 sticky top-0 z-10"><div className="max-w-2xl mx-auto px-4 py-3 flex items-center justify-between"><Link href="/" className="flex items-center gap-2 hover:opacity-75 transition-opacity"><Brain size={20} className="text-[#00d4ff]" /><span className="font-bold text-white text-sm">מתמטיקה + AI</span></Link><Link href="/" className="text-slate-400 hover:text-slate-200 text-sm transition-colors flex items-center gap-1"><ChevronRight size={14} className="rotate-180" />כיתה י״א • 3 יח&quot;ל</Link></div></header>
      <main className="max-w-2xl mx-auto px-4 py-14 space-y-10">
        <div className="text-center space-y-3 animate-[fadeSlideIn_0.4s_ease_both]"><p className="text-purple-400 text-xs font-semibold uppercase tracking-widest">כיתה י״א • 3 יח&quot;ל</p><h1 className="text-4xl font-extrabold">הסתברות</h1><p className="text-slate-400 text-sm">הסתברות בסיסית • הסתברות מותנית • בייס</p></div>
        <div className="grid gap-5 animate-[fadeSlideIn_0.5s_ease_both]">{SUBTOPICS.map(sub=>{const Icon=sub.icon;return(<Link key={sub.id} href={sub.href} className={`card-hover block bg-[#0f172a] border border-slate-700 ${sub.hoverBorder} rounded-2xl p-6 group`} style={sub.glowAnim?{animation:"pulseGlow 3s ease-in-out infinite"}:undefined}><div className="flex items-start gap-5"><div className={`w-12 h-12 rounded-xl ${sub.iconBg} border ${sub.iconBorder} flex items-center justify-center shrink-0`}><Icon size={22} className={sub.iconText}/></div><div className="flex-1 min-w-0"><div className="flex items-center justify-between mb-0.5"><h2 className="text-white font-bold text-xl">{sub.title}</h2><span className={`text-xs font-semibold px-2.5 py-1 rounded-full border ${sub.badgeBg} ${sub.badgeText}`}>תרגול</span></div><p className={`text-xs font-medium mb-2 ${sub.iconText}`}>{sub.subtitle}</p><p className="text-slate-400 text-sm leading-relaxed mb-3">{sub.description}</p><div className="flex flex-wrap gap-2">{sub.chips.map(c=><span key={c} className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-800 border border-slate-700 text-slate-400">{c}</span>)}</div></div><ChevronRight size={18} className={`text-slate-600 ${sub.chevronHover} transition-colors shrink-0 mt-1`}/></div></Link>)})}</div>
        <div className="border-t border-slate-800 pt-6 flex justify-center"><Link href="/" style={{display:"flex",alignItems:"center",gap:6,padding:"8px 14px",background:"#4A4A4A",border:"1px solid #333",borderRadius:10,fontSize:14,fontWeight:600,color:"#FFFFFF",textDecoration:"none"}} onMouseEnter={e=>{(e.currentTarget as HTMLAnchorElement).style.background="#2D2D2D"}} onMouseLeave={e=>{(e.currentTarget as HTMLAnchorElement).style.background="#4A4A4A"}}><span style={{fontSize:16}}>←</span>חזרה</Link></div>
      </main>
    </div>
  );
}
